spring:
  application:
    name: Cliente
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clientes
    username: postgres
    password: cideneT-1
  jpa:
    hibernate:
      ddl-auto: none
      
server:
  address: localhost
  port: 9010
